# This workflow warns and then closes issues and PRs that have had no activity for a specified amount of time.
#
# You can adjust the behavior by modifying this file.
# For more information, see:
# https://github.com/actions/stale
name: Mark stale issues and pull requests

on:
  push:
    branches: [main]
#  schedule:
#  - cron: '00 00 * * *'

jobs:
  stale:

    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

   env:
     AWS_DEFAULT_REGION: ap-southeast-1
     
    steps:
    - name: configureawscredentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: arn:aws:iam::386802427002:role/github-action-roles
        role-session-name: samplerolesession
        aws-region: ${{env.AWS_DEFAULT_REGION}}
        
    - name: Checkout
      uses: actions/checkout@v2

    - name: Some AWS commands
      run: |
        aws s3 ls 
